NUMBER_OF_DAYS = 5
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

NUMBER_OF_PERIODS = 13 # BASED ON SY 2024-2025 SCHED

NO_CONSECUTIVE_CLASS_COST_MULTIPLIER = 0.5
NO_OVERLAPING_LABORATORY_CLASSES_MULTIPLIER = 0.5
NO_MATH_SCIENCE_AFTER_LUNCH_MULTIPLIER = 0.25

